from app.models import db, User, environment, SCHEMA, Book


def seed_books():
    book1 = Book(
        name='Dune',author='Frank Herbert', description=" Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, who would become the mysterious man known as Muad'Dib. He would avenge the traitorous plot against his noble family -- and would bring to fruition humankind's most ancient and unattainable dream. A stunning blend of adventure and mysticism, environmentalism and politics, Dune won the first Nebula Award, shared the Hugo Award, and formed the basis of what is undoubtedly the grandest epic in science fiction.", page_number=74, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1669153623/capstone/t93aqtmfiku41_ucwmfk.webp', genre= 'Fiction', added_by = 1
        )
    book2 = Book(
        name='Kafka on the Shore', author='Haruki Murakami', description='Here we meet a teenage boy, Kafka Tamura, who is on the run, and Nakata, an aging simpleton who is drawn to Kafka for reasons he cannot fathom. As their paths converge, acclaimed author Haruki Murakami enfolds readers in a world where cats talk, fish fall from the sky, and spirits slip out of their bodies to make love or commit murder, in what is a truly remarkable journey.', page_number=505, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1669153939/capstone/41EVg-wdnHL._AC_SY780__ykdk1t.jpg', genre='Fiction', added_by = 2
        )
    book3 = Book(
        name='The Art of War', author='Sun Tzu', description='Water shapes its course according to the nature of the ground over which it flows; the soldier works out his victory in relation to the foe whom he is facing. Therefore, just as water retains no constant shape, so in warfare there are no constant conditions.', page_number=224, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1669154483/capstone/41JFPRxkrLL._AC_SY780__obgp7a.jpg', genre = 'Nonfiction', added_by = 3
        )
    book4 = Book(
        name='A Deadly Education', author='Naomi Novik', description="I decided that Orion Lake needed to die after the second time he saved my life. Everyone loves Orion Lake. Everyone else, that is. Far as I'm concerned, he can keep his flashy combat magic to himself. I'm not joining his pack of adoring fans. I don't need help surviving the Scholomance, even if they do. Forget the hordes of monsters and cursed artifacts, I'm probably the most dangerous thing in the place. Just give me a chance and I'll level mountains and kill untold millions, make myself the dark queen of the world. At least, that's what the world expects. Most of the other students in here would be delighted if Orion killed me like one more evil thing that's crawled out of the drains. Sometimes I think they want me to turn into the evil witch they assume I am. The school certainly does. But the Scholomance isn't getting what it wants from me. And neither is Orion Lake. I may not be anyone's idea of the shining hero, but I'm going to make it out of this place alive, and I'm not going to slaughter thousands to do it, either. Although I'm giving serious consideration to just one.", page_number=338, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1670200289/capstone/download_kmtixb.jpg', genre = 'Fiction', added_by = 1
    )
    book5 = Book(
        name='The Sun Also Rises', author='Ernest Hemingway', description="Originally published in 1926. The Sun Also Rises is Ernest Hemingway's first novel and a classic example of his spare but powerful writing style. A poignant look at the disillusionment and angst of the post-World War 1 generation, the novel introduces two of Hemingway's most unforgettable characters: Jake Barnes and Lady Brett Ashley. The story follows the flamboyant Brett and the hapless Jake as they journey from the wild nightlife of 1920s Paris to the brutal bullfighting rings of Spain with a motley group of expatriates. In his first great literary masterpiece, Hemingway portrays an age of moral bankruptcy, spiritual dissolution, unrealized love, and vanishing illusions.", page_number=279, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1670200625/capstone/The_Sun_Also_Rises__1st_ed._cover_fe2tcr.jpg', genre = 'Fiction', added_by = 1
    )
    book6 = Book(
        name='The Last Graduate', author='Naomi Novik', description="In Wisdom, Shelter. That's the official motto of the Scholomance. I suppose you could even argue that it's true—only the wisdom is hard to come by, so the shelter's rather scant. Our beloved school does its best to devour all its students—but now that I've reached my senior year and have actually won myself a handful of allies, it's suddenly developed a very particular craving for me. And even if I somehow make it through the endless waves of maleficaria that it keeps throwing at me in between grueling homework assignments, I haven't any idea how my allies and I are going to make it through the graduation hall alive. Unless, of course, I finally accept my foretold destiny of dark sorcery and destruction. That would certainly let me sail straight out of here. The course of wisdom, surely. But I'm not giving in—not to the mals, not to fate, and especially not to the Scholomance. I'm going to get myself and my friends out of this hideous place for good—even if it's the last'thing I do.", page_number=389, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671204898/capstone/414X7nVE-eL_vf47pj.jpg', genre = 'Fiction', added_by = 1
    )
    book7 = Book(
        name='The Golden Enclaves', author='Naomi Novik', description="The one thing you never talk about while you're in the Scholomance is what you'll do when you get out. Not even the richest enclaver would tempt fate that way. But it's all we dream about: the hideously slim chance we'll survive to make it out the gates and improbably find ourselves with a life ahead of us, a life outside the Scholomance halls. And now the impossible dream has come true. I'm out, we're all out—and I didn't even have to turn into a monstrous dark witch to make it happen. So much for my great-grandmother's prophecy of doom and destruction. I didn't kill enclavers, I saved them. Me and Orion and our allies. Our graduation plan worked to perfection: We saved everyone and made the world safe for all wizards and brought peace and harmony to all the enclaves everywhere. Ha, only joking! Actually, it's gone all wrong. Someone else has picked up the project of destroying enclaves in my stead, and probably everyone we saved is about to get killed in the brewing enclave war. And the first thing I've got to do now, having miraculously gotten out of the Scholomance, is turn straight around and find a way back in.", page_number=411, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671205044/capstone/51ocOKa4ziL_wnk8k3.jpg', genre = 'Fiction', added_by = 1
    )
    book8 = Book(
        name='A Farewell to Arms', author='Ernest Hemingway', description="Written when Ernest Hemingway was thirty years old and lauded as the best American novel to emerge from World War I, A Farewell to Arms is the unforgettable story of an American ambulance driver on the Italian front and his passion for a beautiful English nurse. Set against the looming horrors of the battlefield—weary, demoralized men marching in the rain during the German attack on Caporetto; the profound struggle between loyalty and desertion—this gripping, semiautobiographical work captures the harsh realities of war and the pain of lovers caught in its inexorable sweep.", page_number=360, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671205286/capstone/41mxgAl2EfL_v8uxxy.jpg', genre = 'Fiction', added_by = 1
    )
    book9 = Book(
        name='A Darker Shade of Magic', author='V.E. Schwab', description="Kell is one of the last Antari—magicians with a rare, coveted ability to travel between parallel Londons; Red, Grey, White, and, once upon a time, Black. Kell was raised in Arnes—Red London—and officially serves the Maresh Empire as an ambassador, traveling between the frequent bloody regime changes in White London and the court of George III in the dullest of Londons, the one without any magic left to see. Unofficially, Kell is a smuggler, servicing people willing to pay for even the smallest glimpses of a world they'll never see. It's a defiant hobby with dangerous consequences, which Kell is now seeing firsthand. After an exchange goes awry, Kell escapes to Grey London and runs into Delilah Bard, a cut-purse with lofty aspirations. She first robs him, then saves him from a deadly enemy, and finally forces Kell to spirit her to another world for a proper adventure. Now perilous magic is afoot, and treachery lurks at every turn. To save all of the worlds, they'll first need to stay alive.", page_number=401, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671205536/capstone/51xXXt6Yw2L_i4ssck.jpg', genre = 'Fiction', added_by = 1
    )
    book10 = Book(
        name='A Gathering of Shadows', author='V.E. Schwab', description="Four months have passed since the shadow stone fell into Kell's possession. Four months since his path crossed with Delilah Bard. Four months since Rhy was wounded and the Dane twins fell, and the stone was cast with Holland's dying body through the rift, and into Black London. In many ways, things have almost returned to normal, though Rhy is more sober, and Kell is now plagued by his guilt. Restless, and having given up smuggling, Kell is visited by dreams of ominous magical events, waking only to think of Lila, who disappeared from the docks like she always meant to do. As Red London finalizes preparations for the Element Games-an extravagant international competition of magic, meant to entertain and keep healthy the ties between neighboring countries-a certain pirate ship draws closer, carrying old friends back into port. But while Red London is caught up in the pageantry and thrills of the Games, another London is coming back to life, and those who were thought to be forever gone have returned. After all, a shadow that was gone in the night reappears in the morning, and so it seems Black London has risen again-and so to keep magic's balance, another London must fall...in V.E. Schwab's A Gathering of Shadows.", page_number=514, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671205627/capstone/51jxJJ7cmZL_k1lc7a.jpg', genre = 'Fiction', added_by = 1
    )
    book11 = Book(
        name='A Conjuring of Light', author='V.E. Schwab', description="As darkness sweeps the Maresh Empire, the once precarious balance of power among the four Londons has reached its breaking point. In the wake of tragedy, Kell—once assumed to be the last surviving Antari—begins to waver under the pressure of competing loyalties. Lila Bard, once a commonplace—but never common—thief, has survived and flourished through a series of magical trials. But now she must learn to control the magic, before it bleeds her dry. An ancient enemy returns to claim a city while a fallen hero tries to save a kingdom in decay. Meanwhile, the disgraced Captain Alucard Emery of the Night Spire collects his crew, attempting a race against time to acquire the impossible.", page_number=642, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671205857/capstone/515M7kmM8rL_h5xvnz.jpg', genre = 'Fiction', added_by = 1
    )
    db.session.add(book1)
    db.session.add(book2)
    db.session.add(book3)
    db.session.add(book4)
    db.session.add(book5)
    db.session.add(book6)
    db.session.add(book7)
    db.session.add(book8)
    db.session.add(book9)
    db.session.add(book10)
    db.session.add(book11)
    db.session.commit()


def undo_books():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.users RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM users")

    db.session.commit()
