from app.models import db, User, environment, SCHEMA, Book


def seed_books():
    book1 = Book(
        name='Dune',author='Frank Herbert', description=" Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, who would become the mysterious man known as Muad'Dib. He would avenge the traitorous plot against his noble family -- and would bring to fruition humankind's most ancient and unattainable dream. A stunning blend of adventure and mysticism, environmentalism and politics, Dune won the first Nebula Award, shared the Hugo Award, and formed the basis of what is undoubtedly the grandest epic in science fiction.", page_number=74, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1669153623/capstone/t93aqtmfiku41_ucwmfk.webp', genre= 'Fiction', added_by = 1
        )
    book2 = Book(
        name='Kafka on the Shore', author='Haruki Murakami', description='Here we meet a teenage boy, Kafka Tamura, who is on the run, and Nakata, an aging simpleton who is drawn to Kafka for reasons he cannot fathom. As their paths converge, acclaimed author Haruki Murakami enfolds readers in a world where cats talk, fish fall from the sky, and spirits slip out of their bodies to make love or commit murder, in what is a truly remarkable journey.', page_number=505, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1669153939/capstone/41EVg-wdnHL._AC_SY780__ykdk1t.jpg', genre='Fiction', added_by = 2
        )
    book3 = Book(
        name='The Art of War', author='Sun Tzu', description='Water shapes its course according to the nature of the ground over which it flows; the soldier works out his victory in relation to the foe whom he is facing. Therefore, just as water retains no constant shape, so in warfare there are no constant conditions.', page_number=224, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1669154483/capstone/41JFPRxkrLL._AC_SY780__obgp7a.jpg', genre = 'Nonfiction', added_by = 3
        )
    book4 = Book(
        name='A Deadly Education', author='Naomi Novik', description="I decided that Orion Lake needed to die after the second time he saved my life. Everyone loves Orion Lake. Everyone else, that is. Far as I'm concerned, he can keep his flashy combat magic to himself. I'm not joining his pack of adoring fans. I don't need help surviving the Scholomance, even if they do. Forget the hordes of monsters and cursed artifacts, I'm probably the most dangerous thing in the place. Just give me a chance and I'll level mountains and kill untold millions, make myself the dark queen of the world. At least, that's what the world expects. Most of the other students in here would be delighted if Orion killed me like one more evil thing that's crawled out of the drains. Sometimes I think they want me to turn into the evil witch they assume I am. The school certainly does. But the Scholomance isn't getting what it wants from me. And neither is Orion Lake. I may not be anyone's idea of the shining hero, but I'm going to make it out of this place alive, and I'm not going to slaughter thousands to do it, either. Although I'm giving serious consideration to just one.", page_number=338, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1670200289/capstone/download_kmtixb.jpg', genre = 'Fiction', added_by = 1
    )
    book5 = Book(
        name='The Sun Also Rises', author='Ernest Hemingway', description="Originally published in 1926. The Sun Also Rises is Ernest Hemingway's first novel and a classic example of his spare but powerful writing style. A poignant look at the disillusionment and angst of the post-World War 1 generation, the novel introduces two of Hemingway's most unforgettable characters: Jake Barnes and Lady Brett Ashley. The story follows the flamboyant Brett and the hapless Jake as they journey from the wild nightlife of 1920s Paris to the brutal bullfighting rings of Spain with a motley group of expatriates. In his first great literary masterpiece, Hemingway portrays an age of moral bankruptcy, spiritual dissolution, unrealized love, and vanishing illusions.", page_number=279, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1670200625/capstone/The_Sun_Also_Rises__1st_ed._cover_fe2tcr.jpg', genre = 'Fiction', added_by = 1
    )
    book6 = Book(
        name='The Last Graduate', author='Naomi Novik', description="In Wisdom, Shelter. That's the official motto of the Scholomance. I suppose you could even argue that it's true—only the wisdom is hard to come by, so the shelter's rather scant. Our beloved school does its best to devour all its students—but now that I've reached my senior year and have actually won myself a handful of allies, it's suddenly developed a very particular craving for me. And even if I somehow make it through the endless waves of maleficaria that it keeps throwing at me in between grueling homework assignments, I haven't any idea how my allies and I are going to make it through the graduation hall alive. Unless, of course, I finally accept my foretold destiny of dark sorcery and destruction. That would certainly let me sail straight out of here. The course of wisdom, surely. But I'm not giving in—not to the mals, not to fate, and especially not to the Scholomance. I'm going to get myself and my friends out of this hideous place for good—even if it's the last'thing I do.", page_number=389, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671204898/capstone/414X7nVE-eL_vf47pj.jpg', genre = 'Fiction', added_by = 1
    )
    book7 = Book(
        name='The Golden Enclaves', author='Naomi Novik', description="The one thing you never talk about while you're in the Scholomance is what you'll do when you get out. Not even the richest enclaver would tempt fate that way. But it's all we dream about: the hideously slim chance we'll survive to make it out the gates and improbably find ourselves with a life ahead of us, a life outside the Scholomance halls. And now the impossible dream has come true. I'm out, we're all out—and I didn't even have to turn into a monstrous dark witch to make it happen. So much for my great-grandmother's prophecy of doom and destruction. I didn't kill enclavers, I saved them. Me and Orion and our allies. Our graduation plan worked to perfection: We saved everyone and made the world safe for all wizards and brought peace and harmony to all the enclaves everywhere. Ha, only joking! Actually, it's gone all wrong. Someone else has picked up the project of destroying enclaves in my stead, and probably everyone we saved is about to get killed in the brewing enclave war. And the first thing I've got to do now, having miraculously gotten out of the Scholomance, is turn straight around and find a way back in.", page_number=411, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671205044/capstone/51ocOKa4ziL_wnk8k3.jpg', genre = 'Fiction', added_by = 1
    )
    book8 = Book(
        name='A Farewell to Arms', author='Ernest Hemingway', description="Written when Ernest Hemingway was thirty years old and lauded as the best American novel to emerge from World War I, A Farewell to Arms is the unforgettable story of an American ambulance driver on the Italian front and his passion for a beautiful English nurse. Set against the looming horrors of the battlefield—weary, demoralized men marching in the rain during the German attack on Caporetto; the profound struggle between loyalty and desertion—this gripping, semiautobiographical work captures the harsh realities of war and the pain of lovers caught in its inexorable sweep.", page_number=360, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671205286/capstone/41mxgAl2EfL_v8uxxy.jpg', genre = 'Fiction', added_by = 1
    )
    book9 = Book(
        name='A Darker Shade of Magic', author='V.E. Schwab', description="Kell is one of the last Antari—magicians with a rare, coveted ability to travel between parallel Londons; Red, Grey, White, and, once upon a time, Black. Kell was raised in Arnes—Red London—and officially serves the Maresh Empire as an ambassador, traveling between the frequent bloody regime changes in White London and the court of George III in the dullest of Londons, the one without any magic left to see. Unofficially, Kell is a smuggler, servicing people willing to pay for even the smallest glimpses of a world they'll never see. It's a defiant hobby with dangerous consequences, which Kell is now seeing firsthand. After an exchange goes awry, Kell escapes to Grey London and runs into Delilah Bard, a cut-purse with lofty aspirations. She first robs him, then saves him from a deadly enemy, and finally forces Kell to spirit her to another world for a proper adventure. Now perilous magic is afoot, and treachery lurks at every turn. To save all of the worlds, they'll first need to stay alive.", page_number=401, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671205536/capstone/51xXXt6Yw2L_i4ssck.jpg', genre = 'Fiction', added_by = 1
    )
    book10 = Book(
        name='A Gathering of Shadows', author='V.E. Schwab', description="Four months have passed since the shadow stone fell into Kell's possession. Four months since his path crossed with Delilah Bard. Four months since Rhy was wounded and the Dane twins fell, and the stone was cast with Holland's dying body through the rift, and into Black London. In many ways, things have almost returned to normal, though Rhy is more sober, and Kell is now plagued by his guilt. Restless, and having given up smuggling, Kell is visited by dreams of ominous magical events, waking only to think of Lila, who disappeared from the docks like she always meant to do. As Red London finalizes preparations for the Element Games-an extravagant international competition of magic, meant to entertain and keep healthy the ties between neighboring countries-a certain pirate ship draws closer, carrying old friends back into port. But while Red London is caught up in the pageantry and thrills of the Games, another London is coming back to life, and those who were thought to be forever gone have returned. After all, a shadow that was gone in the night reappears in the morning, and so it seems Black London has risen again-and so to keep magic's balance, another London must fall...in V.E. Schwab's A Gathering of Shadows.", page_number=514, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671205627/capstone/51jxJJ7cmZL_k1lc7a.jpg', genre = 'Fiction', added_by = 1
    )
    book11 = Book(
        name='A Conjuring of Light', author='V.E. Schwab', description="As darkness sweeps the Maresh Empire, the once precarious balance of power among the four Londons has reached its breaking point. In the wake of tragedy, Kell—once assumed to be the last surviving Antari—begins to waver under the pressure of competing loyalties. Lila Bard, once a commonplace—but never common—thief, has survived and flourished through a series of magical trials. But now she must learn to control the magic, before it bleeds her dry. An ancient enemy returns to claim a city while a fallen hero tries to save a kingdom in decay. Meanwhile, the disgraced Captain Alucard Emery of the Night Spire collects his crew, attempting a race against time to acquire the impossible.", page_number=642, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1671205857/capstone/515M7kmM8rL_h5xvnz.jpg', genre = 'Fiction', added_by = 1
    )
    book12 = Book(
        name="Harry Potter and the Sorcerer's Stone", author='J.K. Rowling', description="Harry Potter has no idea how famous he is. That's because he's being raised by his miserable aunt and uncle who are terrified Harry will learn that he's really a wizard, just as his parents were. But everything changes when Harry is summoned to attend an infamous school for wizards, and he begins to discover some clues about his illustrious birthright. From the surprising way he is greeted by a lovable giant, to the unique curriculum and colorful faculty at his unusual school, Harry finds himself drawn deep inside a mystical world he never knew existed and closer to his own noble destiny.", page_number=309, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673877684/capstone/81iqZ2HHD-L_qifii2.jpg', genre = 'Fiction', added_by = 2
    )
    book13 = Book(
        name="Harry Potter and the Chamber of Secrets", author='J.K. Rowling', description="The Dursleys were so mean that hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he's packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike. And strike it does. For in Harry's second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor, Gilderoy Lockheart, a spirit named Moaning Myrtle who haunts the girls' bathroom, and the unwanted attentions of Ron Weasley's younger sister, Ginny. But each of these seem minor annoyances when the real trouble begins, and someone--or something--starts turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possibly be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects... Harry Potter himself?", page_number=341, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673877793/capstone/91OINeHnJGL_wujjdt.jpg', genre = 'Fiction', added_by = 2
    )
    book14 = Book(
        name="Harry Potter and the Prisoner of Azkaban", author='J.K. Rowling', description="For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.Now he has escaped, leaving only two clues as to where he might be headed: Harry Potter's defeat of You-Know-Who was Black's downfall as well. And the Azkaban guards heard Black muttering in his sleep, 'He's at Hogwarts . . . he's at Hogwarts.' Harry Potter isn't safe, not even within the walls of his magical school, surrounded by his friends. Because on top of it all, there may well be a traitor in their midst.", page_number=435, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673877988/capstone/81lAPl9Fl0L_eutbgy.jpg', genre = 'Fiction', added_by = 2
    )
    book15 = Book(
        name="Harry Potter and the Goblet of Fire", author='J.K. Rowling', description="Harry Potter is midway through his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup. He wants to find out about the mysterious event that's supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn't happened for a hundred years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he's not normal - even by wizarding standards. And in his case, different can be deadly.", page_number=752, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673878062/capstone/91gZX7sjnpL_pbj72c.jpg', genre = 'Fiction', added_by = 2
    )
    book16 = Book(
        name="Harry Potter and the Order of the Pheonix", author='J.K. Rowling', description="There is a door at the end of a silent corridor. And it's haunting Harry Potter's dreams. Why else would he be waking in the middle of the night, screaming in terror? It's not just the upcoming O.W.L. exams; a new teacher with a personality like poisoned honey; a venomous, disgruntled house-elf; or even the growing threat of He-Who-Must-Not-Be-Named. Now Harry Potter is faced with the unreliability of the very government of the magical world and the impotence of the authorities at Hogwarts. Despite this (or perhaps because of it), he finds depth and strength in his friends, beyond what even he knew; boundless loyalty; and unbearable sacrifice.", page_number=576, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673878314/capstone/516c41oodRL_i49scl.jpg', genre = 'Fiction', added_by = 2
    )
    book17 = Book(
        name="Harry Potter and the Half-Blood Prince", author='J.K. Rowling', description="There it was, hanging in the sky above the school: the blazing green skull with a serpent tongue, the mark Death Eaters left behind whenever they had entered a building...wherever they had murdered... When Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Secrets and suspicion are spreading through the wizarding world, and Hogwarts itself is not safe. Harry is convinced that Malfoy bears the Dark Mark: there is a Death Eater amongst them. Harry will need powerful magic and true friends as he explores Voldemort's darkest secrets, and Dumbledore prepares him to face his destiny...", page_number=652, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673878458/capstone/61sXBXmAWML_btfofd.jpg', genre = 'Fiction', added_by = 2
    )
    book18 = Book(
        name="Harry Potter and the Deathly Hallows", author='J.K. Rowling', description="'Give me Harry Potter,' said Voldemort's voice, 'and none shall be harmed. Give me Harry Potter, and I shall leave the school untouched. Give me Harry Potter, and you will be rewarded.' As he climbs into the sidecar of Hagrid's motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind. The protective charm that has kept Harry safe until now is broken, but he cannot keep hiding. The Dark Lord is breathing fear into everything Harry loves and to stop him Harry will have to find and destroy the remaining Horcruxes. The final battle must begin - Harry must stand and face his enemy...", page_number=784, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673878511/capstone/811t1pfIZXL_kvuex2.jpg', genre = 'Fiction', added_by = 2
    )
    book19 = Book(
        name="A Game of Thrones", author='George R. R. Martin', description="Winter is coming. Such is the stern motto of House Stark, the northernmost of the fiefdoms that owe allegiance to King Robert Baratheon in far-off King's Landing. There Eddard Stark of Winterfell rules in Robert's name. There his family dwells in peace and comfort: his proud wife, Catelyn; his sons Robb, Brandon, and Rickon; his daughters Sansa and Arya; and his bastard son, Jon Snow. Far to the north, behind the towering Wall, lie savage Wildings and worse—unnatural things relegated to myth during the centuries-long summer, but proving all too real and all too deadly in the turning of the season. Yet a more immediate threat lurks to the south, where Jon Arryn, the Hand of the King, has died under mysterious circumstances. Now Robert is riding north to Winterfell, bringing his queen, the lovely but cold Cersei, his son, the cruel, vainglorious Prince Joffrey, and the queen's brothers Jaime and Tyrion of the powerful and wealthy House Lannister—the first a swordsman without equal, the second a dwarf whose stunted stature belies a brilliant mind. All are heading for Winterfell and a fateful encounter that will change the course of kingdoms. Meanwhile, across the Narrow Sea, Prince Viserys, heir of the fallen House Targaryen, which once ruled all of Westeros, schemes to reclaim the throne with an army of barbarian Dothraki—whose loyalty he will purchase in the only coin left to him: his beautiful yet innocent sister, Daenerys.", page_number=704, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673879027/capstone/914uNuOXwSL_fnxlx1.jpg', genre = 'Fiction', added_by = 3
    )
    book20 = Book(
        name="A Clash of Kings", author='George R. R. Martin', description="Of the five contenders for power, one is dead, another in disfavor, and still the wars rage as violently as ever, as alliances are made and broken. Joffrey, of House Lannister, sits on the Iron Throne, the uneasy ruler of the land of the Seven Kingdoms. His most bitter rival, Lord Stannis, stands defeated and disgraced, the victim of the jealous sorceress who holds him in her evil thrall. But young Robb, of House Stark, still rules the North from the fortress of Riverrun. Robb plots against his despised Lannister enemies, even as they hold his sister hostage at King's Landing, the seat of the Iron Throne. Meanwhile, making her way across a blood-drenched continent is the exiled queen, Daenerys, mistress of the only three dragons still left in the world. . . . But as opposing forces maneuver for the final titanic showdown, an army of barbaric wildlings arrives from the outermost line of civilization. In their vanguard is a horde of mythical Others—a supernatural army of the living dead whose animated corpses are unstoppable. As the future of the land hangs in the balance, no one will rest until the Seven Kingdoms have exploded in a veritable storm of swords. . . .", page_number=1008, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673879263/capstone/91d-77kn-dL_f16zaa.jpg', genre = 'Fiction', added_by = 3
    )
    book21 = Book(
        name="A Feast for Crows", author='George R. R. Martin', description="It seems too good to be true. After centuries of bitter strife and fatal treachery, the seven powers dividing the land have decimated one another into an uneasy truce. Or so it appears. . . . With the death of the monstrous King Joffrey, Cersei is ruling as regent in King's Landing. Robb Stark's demise has broken the back of the Northern rebels, and his siblings are scattered throughout the kingdom like seeds on barren soil. Few legitimate claims to the once desperately sought Iron Throne still exist—or they are held in hands too weak or too distant to wield them effectively. The war, which raged out of control for so long, has burned itself out. But as in the aftermath of any climactic struggle, it is not long before the survivors, outlaws, renegades, and carrion eaters start to gather, picking over the bones of the dead and fighting for the spoils of the soon-to-be dead. Now in the Seven Kingdoms, as the human crows assemble over a banquet of ashes, daring new plots and dangerous new alliances are formed, while surprising faces—some familiar, others only just appearing—are seen emerging from an ominous twilight of past struggles and chaos to take up the challenges ahead. It is a time when the wise and the ambitious, the deceitful and the strong will acquire the skills, the power, and the magic to survive the stark and terrible times that lie before them. It is a time for nobles and commoners, soldiers and sorcerers, assassins and sages to come together and stake their fortunes . . . and their lives. For at a feast for crows, many are the guests—but only a few are the survivors.", page_number=784, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673879371/capstone/91eJCheb4gL_f4u9vx.jpg', genre = 'Fiction', added_by = 3
    )
    book22 = Book(
        name="A Dance with Dragons", author='George R. R. Martin', description="In the aftermath of a colossal battle, the future of the Seven Kingdoms hangs in the balance—beset by newly emerging threats from every direction. In the east, Daenerys Targaryen, the last scion of House Targaryen, rules with her three dragons as queen of a city built on dust and death. But Daenerys has thousands of enemies, and many have set out to find her. As they gather, one young man embarks upon his own quest for the queen, with an entirely different goal in mind. Fleeing from Westeros with a price on his head, Tyrion Lannister, too, is making his way to Daenerys. But his newest allies in this quest are not the rag-tag band they seem, and at their heart lies one who could undo Daenerys's claim to Westeros forever. Meanwhile, to the north lies the mammoth Wall of ice and stone—a structure only as strong as those guarding it. There, Jon Snow, 998th Lord Commander of the Night's Watch, will face his greatest challenge. For he has powerful foes not only within the Watch but also beyond, in the land of the creatures of ice. From all corners, bitter conflicts reignite, intimate betrayals are perpetrated, and a grand cast of outlaws and priests, soldiers and skinchangers, nobles and slaves, will face seemingly insurmountable obstacles. Some will fail, others will grow in the strength of darkness. But in a time of rising restlessness, the tides of destiny and politics will lead inevitably to the greatest dance of all.", page_number=1056, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673879469/capstone/91Og8YcsClL_id62zi.jpg', genre = 'Fiction', added_by = 3
    )
    book23 = Book(
        name="Killing Floor", author='Lee Child', description="Ex-military policeman Jack Reacher is a drifter. He's just passing through Margrave, Georgia, and in less than an hour, he's arrested for murder. Not much of a welcome. All Reacher knows is that he didn't kill anybody. At least not here. Not lately. But he doesn't stand a chance of convincing anyone. Not in Margrave, Georgia. Not a chance in hell.", page_number=576, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673891626/capstone/71mYhQ0lfGL_oapulx.jpg', genre = 'Fiction', added_by = 4
    )
    book24 = Book(
        name="Die Trying", author='Lee Child', description="Jack Reacher is an innocent bystander when he witnesses a woman kidnapped off a Chicago street in broad daylight. In the wrong place at the wrong time, he's kidnapped with her. Chained together, locked in the back of a stifling van, and racing across America to an unknown destination for an unknown purpose, they're at the mercy of a group of men demanding an impossible ransom. Because this mysterious woman is worth more than Reacher ever suspected. Now he has to save them both—from the inside out—or die trying....", page_number=567, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673891760/capstone/916vm4YOvcL_wahvmh.jpg', genre = 'Fiction', added_by = 4
    )
    book25 = Book(
        name="Tripwire", author='Lee Child', description="Ex military policeman Jack Reacher is enjoying the lazy anonymity of Key West when a stranger shows up asking for him. He's got a lot of questions. Reacher does too, especially after the guy turns up dead. The answers lead Reacher on a cold trail back to New York, to the tenuous confidence of an alluring woman, and the dangerous corners of his own past.", page_number=608, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673891830/capstone/81pHuQ3W06L_czzysf.jpg', genre = 'Fiction', added_by = 4
    )
    book26 = Book(
        name="The Amazing Adventures of Kavalier & Clay", author='Michael Chabon', description="A young escape artist and budding magician named Joe Kavalier arrives on the doorstep of his cousin, Sammy Clay. While the long shadow of Hitler falls across Europe, America is happily in thrall to the Golden Age of comic books, and in a distant corner of Brooklyn, Sammy is looking for a way to cash in on the craze. He finds the ideal partner in the aloof, artistically gifted Joe, and together they embark on an adventure that takes them deep into the heart of Manhattan, and the heart of old-fashioned American ambition. From the shared fears, dreams, and desires of two teenage boys, they spin comic book tales of the heroic, fascist-fighting Escapist and the beautiful, mysterious Luna Moth, otherworldly mistress of the night. Climbing from the streets of Brooklyn to the top of the Empire State Building, Joe and Sammy carve out lives, and careers, as vivid as cyan and magenta ink.", page_number=684, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673892066/capstone/81mqEtRmHlL_igvt64.jpg', genre = 'Fiction', added_by = 5
    )
    book27 = Book(
        name="The Dog Master: A Novel of the First Dog", author='W. Bruce Cameron', description="Thirty thousand years ago, ice was storming the planet. Among the species forced out of the trees and onto the steppes by the advancing cold was modern man, who was both predator and prey. No stranger to the experiences that make us human--a mother's love and a father's betrayal, tribal war and increasing famine, political intrigue and forbidden love, joy and hope and devastating loss--our ancestors competed for scant resources in a brutal landscape. Mankind stood on the cold brink of extinction...but they had a unique advantage over other species, a new technology--domesticated wolves.", page_number=416, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673892267/capstone/912t9rDZTCL_d8e48s.jpg', genre = 'Fiction', added_by = 6
    )
    book28 = Book(
        name="The Fellowship Of The Ring", author='J.R.R Tolkien', description="In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.", page_number=432, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673892551/capstone/713fuKZOVpL_vrckp3.jpg', genre = 'Fiction', added_by = 6
    )
    book29 = Book(
        name="The Two Towers", author='J.R.R Tolkien', description="Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go.", page_number=352, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673892627/capstone/71SIIh5j7wL_c4o0cr.jpg', genre = 'Fiction', added_by = 6
    )
    book30 = Book(
        name="The Return of the King", author='J.R.R Tolkien', description="As the shadow of Mordor grows across the land, the Companions of the Ring have become involved in separate adventures. Aragorn, revealed as the hidden heir of the ancient Kings of the West, has joined with the Riders of Rohan against the forces of Isengard and takes part in the desperate battle of the Hornburg. Merry and Pippin, captured by Orcs, escape into Fangorn Forest and there encounter the Ents. Gandalf has miraculously returned and defeated the evil wizard, Saruman. Sam has left his master for dead after a battle with the giant spider, Shelob; but Frodo is still alive—now in the foul hands of the Orcs. Meanwhile, the armies of the Dark Lord are massing as the One Ring draws ever nearer to the Cracks of Doom.", page_number=432, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673892702/capstone/71BTBGRXp3L_tqat2w.jpg', genre = 'Fiction', added_by = 6
    )
    book31 = Book(
        name="The Hobbit", author='J.R.R Tolkien', description="Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure. They have launched a plot to raid the treasure hoard guarded by Smaug the Magnificent, a large and very dangerous dragon. Bilbo reluctantly joins their quest, unaware that on his journey to the Lonely Mountain he will encounter both a magic ring and a frightening creature known as Gollum.", page_number=322, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1670254108/capstone/download_xocdrr.jpg', genre = 'Fiction', added_by = 6
    )
    book32 = Book(
        name="The Silmarillion", author='J.R.R Tolkien', description="The story of the creation of the world and of the First Age, this is the ancient drama to which the characters in The Lord of the Rings look back and in whose events some of them, such as Elrond and Galadriel, took part. The three Silmarils were jewels created by Fëanor, most gifted of the Elves. Within them was imprisoned the Light of the Two Trees of Valinor before the Trees themselves were destroyed by Morgoth, the first Dark Lord. Thereafter, the unsullied Light of Valinor lived on only in the Silmarils, but they were seized by Morgoth and set in his crown, which was guarded in the impenetrable fortress of Angband in the north of Middle-earth. The Silmarillion is the history of the rebellion of Fëanor and his kindred against the gods, their exile from Valinor and return to Middle-earth, and their war, hopeless despite all their heroism, against the great Enemy.", page_number=481, cover_image='https://res.cloudinary.com/dydhvazpw/image/upload/v1673892907/capstone/61qig67Ig8L_mfqjlv.jpg', genre = 'Fiction', added_by = 6
    )
    db.session.add(book1)
    db.session.add(book2)
    db.session.add(book3)
    db.session.add(book4)
    db.session.add(book5)
    db.session.add(book6)
    db.session.add(book7)
    db.session.add(book8)
    db.session.add(book9)
    db.session.add(book10)
    db.session.add(book11)
    db.session.add(book12)
    db.session.add(book13)
    db.session.add(book14)
    db.session.add(book15)
    db.session.add(book16)
    db.session.add(book17)
    db.session.add(book18)
    db.session.add(book19)
    db.session.add(book20)
    db.session.add(book21)
    db.session.add(book22)
    db.session.commit()


def undo_books():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.users RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM users")

    db.session.commit()
